export const EMOJI = [
    { id: '1',  emoji: '🚶', name: 'Walking' },
    { id: '2',  emoji: '🏃', name: 'Running' },
    { id: '3',  emoji: '🚴', name: 'Cycling' },
    { id: '4',  emoji: '🏋️', name: 'Weightlifting' },
    { id: '5',  emoji: '🧘', name: 'Yoga' },
    { id: '6',  emoji: '💧', name: 'Water' },
    { id: '7',  emoji: '🍎', name: 'Healthy Eating' },
    { id: '8',  emoji: '🥗', name: 'Salad' },
    { id: '9',  emoji: '📖', name: 'Reading' },
    { id: '10', emoji: '✍️', name: 'Writing' },
    { id: '11', emoji: '🎸', name: 'Music' },
    { id: '12', emoji: '🎨', name: 'Art' },
    { id: '13', emoji: '💻', name: 'Coding' },
    { id: '14', emoji: '🧹', name: 'Cleaning' },
    { id: '15', emoji: '🌱', name: 'Gardening' },
    { id: '16', emoji: '💊', name: 'Medicine' },
    { id: '17', emoji: '💤', name: 'Sleep' },
    { id: '18', emoji: '🧠', name: 'Mindfulness' },
    { id: '19', emoji: '🤝', name: 'Social' },
    { id: '20', emoji: '💰', name: 'Finance' },
];
