export const HABITS = [
    {id: 'water',      emoji: '💧', text: 'Drink water'},
    {id: 'run',        emoji: '🏃🏻‍♀️', text: 'Run'},
    {id: 'read',       emoji: '📖', text: 'Read books'},
    {id: 'meditation', emoji: '🧘🏻‍♀️', text: 'Meditate'},
    {id: 'study',      emoji: '🧑🏻‍💻‍️', text: 'Study'},
    {id: 'journal',    emoji: '📕', text: 'Journal'},
    {id: 'plant',      emoji: '🌿‍', text: 'Grow plants'},
    {id: 'sleep',      emoji: '😴', text: 'Sleep'},
    {id: 'exercise',   emoji: '💪', text: 'Exercise'},
    {id: 'walk',       emoji: '🚶‍♂️', text: 'Walk'},
    {id: 'stretching', emoji: '🙆‍♂️', text: 'Stretching'},
    {id: 'vitamin',    emoji: '💊', text: 'Take vitamins'},
    {id: 'clean',      emoji: '🧹', text: 'Clean up'},
    {id: 'coding',     emoji: '💻', text: 'Coding'},
    {id: 'music',      emoji: '🎸', text: 'Practice music'},
    {id: 'skincare',   emoji: '🧴', text: 'Skincare routine'},
    {id: 'no-sugar',   emoji: '🍎', text: 'No sugar'},
    {id: 'language',   emoji: '🌎', text: 'Learn a language'},
    {id: 'tea',        emoji: '🍵', text: 'Drink tea'},
    {id: 'write',      emoji: '✍️', text: 'Write'},
    {id: 'yoga',       emoji: '🧘', text: 'Yoga'},
    {id: 'cooking',    emoji: '👨‍🍳', text: 'Cooking'}
]
